Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	
	config.vm.define :ci do |ci_config|
		ci_config.vm.network "private_network", ip: "192.168.50.10"

		ci_config.vm.provision "file", source: "ssh-keys/id_rsa", destination: "id_rsa"

		ci_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/ci.yml"
		end
	end

	config.vm.define :db do |db_config|
		db_config.vm.network "private_network", ip: "192.168.50.11"

		db_config.vm.provision "file", source: "db/script.sql", destination: "script.sql"
		db_config.vm.provision "file", source: "db/mysqld.cnf", destination: "mysqld.cnf"

		db_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/db.yml"
		end
	end
	
	config.vm.define :web do |web_config|
		web_config.vm.network "private_network", ip: "192.168.50.12"

		web_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/web.yml"
		end
	end
end